name: Lucian Marin
description: Designer
url: http://lucianmarin.com

#pygments: false
permalink: /archive/:title.html

markdown: redcarpet

relative_permalinks: false

exclude: [readme.md]
include: [.htaccess]